#!/usr/bin/env bash
#shellcheck shell=bash
set -euo pipefail

# Parse arguments
VERBOSE=0
INVENTORY_FILE=""
while [[ $# -gt 0 ]]; do
    case $1 in
        -v|--verbose)
            VERBOSE=1
            shift
            ;;
        -i|--inventory)
            INVENTORY_FILE="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [-v|--verbose] [-i|--inventory FILE]"
            exit 1
            ;;
    esac
done

# Function to run commands with optional verbosity
run_cmd() {
    if [[ $VERBOSE -eq 1 ]]; then
        echo "Running: $*"
    fi
    "$@"
}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}INFO:${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}WARN:${NC} $1" >&2
}

log_error() {
    echo -e "${RED}ERROR:${NC} $1" >&2
}

# Function to prompt for inventory variables and create temporary inventory
create_inventory() {
    log_info "Inventory file not found. Creating temporary inventory..."

    # Prompt for basic user configuration
    read -r -p "Enter username (default: user): " username
    username="${username:-user}"

    read -r -p "Enter UID (default: 1000): " uid
    uid="${uid:-1000}"

    read -r -p "Enter GID (default: 1000): " gid
    gid="${gid:-1000}"

    read -r -p "Enter home directory (default: /home/$username): " home
    home="${home:-/home/$username}"

    read -r -p "Enter shell (default: /bin/bash): " shell
    shell="${shell:-/bin/bash}"

    read -r -p "Enable sudo? (y/n, default: y): " sudo_enable
    sudo_enable="${sudo_enable:-y}"

    user_sudo=$([[ "$sudo_enable" =~ ^[Yy]$ ]] && echo "true" || echo "false")

    # Create temporary inventory file
    cat > "$INVENTORY_FILE" << EOF
# Temporary inventory generated by bootstrap.sh
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

      users:
        - name: '$username'
          comment: '$username user'
          uid: '$uid'
          gid: '$gid'
          group_name: '$username'
          home: '$home'
          shell: '$shell'
          extra_groups: ['sudo']
          user_sudo: $user_sudo
          user_ssh_keys: true
          state: 'present'
EOF

    echo "✓ Temporary inventory created at $INVENTORY_FILE"
}

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root or with sudo"
    exit 1
fi

# Get script directory
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Change to script directory
pushd "$DIR" &>/dev/null || exit 1

# Default values
UV_INSTALL_DIR="${UV_INSTALL_DIR:-/tmp/uv}"
UV_INSTALL_SCRIPT="${UV_INSTALL_SCRIPT:-https://astral.sh/uv/install.sh}"
COLLECTION="${COLLECTION:-git+https://github.com/markfaine/net-markfaine.git}"
COLLECTION_BRANCH="${COLLECTION_BRANCH:-main}"
INVENTORY_FILE="${INVENTORY_FILE:-$DIR/inventory.yml}"

function install_dependencies() {
    log_info "Installing system dependencies..."
    run_cmd apt update
    run_cmd apt install -y curl wget git
    echo "✓ Dependencies installed"
}

function install_uv() {
    log_info "Installing uv..."
    if [[ -x "$UV_INSTALL_DIR/bin/uv" ]]; then
        echo "✓ uv already installed"
        return
    fi
    mkdir -p "$UV_INSTALL_DIR"
    run_cmd curl -LsSf "$UV_INSTALL_SCRIPT" | env UV_INSTALL_DIR="$UV_INSTALL_DIR" sh
    echo "✓ uv installed"
}

function install_collection() {
    log_info "Installing Ansible collection..."
    run_cmd "$UV_INSTALL_DIR/bin/uvx" --from ansible-core ansible-galaxy collection install -f "$COLLECTION,$COLLECTION_BRANCH"
    echo "✓ Collection installed"
}

function run_playbook() {
    log_info "Running Ansible playbook..."
    local playbook_cmd=("$UV_INSTALL_DIR/bin/uvx" --with passlib --from ansible-core ansible-playbook)
    playbook_cmd+=(-i "$INVENTORY_FILE")
    playbook_cmd+=(~/.ansible/collections/ansible_collections/net/markfaine/playbooks/site.yml)

    export ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP="true"
    export ANSIBLE_REMOTE_TEMP="/tmp/.ansible/tmp"
    export ANSIBLE_PIPELINING="true"
    export ANSIBLE_VERBOSITY="${ANSIBLE_VERBOSITY:-0}"

    run_cmd "${playbook_cmd[@]}"
    echo "✓ Playbook completed"
}

# Main execution
log_info "Starting bootstrap process..."

# Check if inventory exists, create if not
if [[ ! -f "$INVENTORY_FILE" ]]; then
    create_inventory
fi

install_dependencies
install_uv
install_collection
run_playbook

echo "✓ Bootstrap complete!"

# Return to original directory
popd &>/dev/null || exit 1
