---
- name: Cleanup external hosts
  hosts: all
  gather_facts: false
  ignore_unreachable: true
  environment:
    SMDEV_CONTAINER_OFF: true

  tasks:
    - name: Unregister system
      ansible.builtin.redhat_subscription:
        state: absent
      become: true
      ignore_errors: true
      environment: "{{ proxy_env | default({}) }}"

    - name: Insights Unregister
      nats.default.insights_register:
        state: absent
      become: true
      ignore_errors: true
      environment: "{{ proxy_env | default({}) }}"
