---
- name: Set user home directory as fact
  ansible.builtin.set_fact:
    homedir: "{{ ansible_env.HOME }}"
  become: true
  become_user: "{{ user_name }}"

- name: Include task for state
  ansible.builtin.include_tasks:
    file: "{{ state | default('present') }}.yml"
  when:
    - ansible_os_family is defined and ansible_os_family == "Debian"
    - state is not defined or state in ['present', 'absent']
