---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars_files:
    - vars.yml
  tasks:

    - name: remove vm
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs | default(false) }}"
        name: "{{ item.name }}"
        state: absent
        force: yes
        proxy_host: 192.100.9.85
        proxy_port: 3128
      delegate_to: localhost
      loop: "{{ molecule_yml.platforms }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: server.changed | default(false) | bool
