---
- name: Remove packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: absent
  become: true
  environment: "{{ proxy_env | default({}) }}"
  notify: systemd-daemon-reload

- name: Remove additional packages
  ansible.builtin.apt:
    name: "{{ docker_remove_packages }}"
    state: absent
  become: true
  environment: "{{ proxy_env | default({}) }}"
  notify: systemd-daemon-reload

- name: Remove docker systemd drop-in directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ docker_service_name }}.service.d"
    state: absent
  become: true
  notify: systemd-daemon-reload

- name: Remove docker config dir
  ansible.builtin.file:
    path: "{{ docker_config_dir }}"
    state: absent
  become: true

- name: Remove docker data dir
  ansible.builtin.file:
    path: "{{ docker_data_dir }}"
    state: absent
  become: true

- name: Remove the user to the group 'docker'
  ansible.builtin.command: usermod -rG docker "{{ user_name }}"
  changed_when: false
  become: true
  tags: skip_ansible_lint
