---
- name: Remove nvim
  ansible.builtin.file:
    path: "{{ nvim_install_dir }}"
    state: absent
  become: true

- name: Find nvim config links
  ansible.builtin.find:
    paths: "{{ user_homedir | default('/home/' + user_name) }}/.config/"
    patterns: 'nvim'
    hidden: true
    file_type: link
    recurse: false
  become: true
  register: nvim_config_links

- name: Delete nvim config links
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  become: true
  become_user: "{{ user_name }}"
  loop: "{{ nvim_config_links.files | default([]) }}"
